# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: increase

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "src/Volvox.Apollo.Web/ClientApp"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    assignees:
      - "codingsamuel"
    labels:
      - "frontend"
      - "dependencies"
      
  # Maintain dependencies for NuGet
  - package-ecosystem: "nuget"
  directory: "/"
  schedule:
    interval: "daily"
  versioning-strategy: increase
  assignees:
    - "billchirico"
  labels:
    - "backend"
    - ".NET"
    - "dependencies"
  registries:
    nuget-azure-devops:
      type: nuget-feed
      url: https://pkgs.dev.azure.com/.../_packaging/My_Feed/nuget/v3/index.json
      token: ${{secrets.MY_AZURE_DEVOPS_TOKEN}}


  # Maintain dependencies for all dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    allow:
      - dependency-type: "all"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    assignees:
      - "billchirico"
    labels:
      - "github-actions"
      - "dependencies"

  # Maintain dependencies for all dependencies
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    allow:
      - dependency-type: "all"
